CREATE TABLE EQUIPAMENTO (ID INTEGER NOT NULL, DISPONIVEL TINYINT(1) default 0, NOME VARCHAR(255), PRIMARY KEY (ID))
CREATE TABLE USUARIO (IDUSUARIO BIGINT NOT NULL, LOGIN VARCHAR(255), NOME VARCHAR(255), SIAPE VARCHAR(255), STATUS TINYINT(1) default 0, PRIMARY KEY (IDUSUARIO))
CREATE TABLE SEQUENCE (SEQ_NAME VARCHAR(50) NOT NULL, SEQ_COUNT DECIMAL(38), PRIMARY KEY (SEQ_NAME))
INSERT INTO SEQUENCE(SEQ_NAME, SEQ_COUNT) values ('SEQ_GEN', 0)
