ALTER TABLE USUARIO_CATEGORIA DROP FOREIGN KEY FK_USUARIO_CATEGORIA_listCategoria_IDCATEGORIA
ALTER TABLE USUARIO_CATEGORIA DROP FOREIGN KEY FK_USUARIO_CATEGORIA_Usuario_IDUSUARIO
DROP TABLE CATEGORIA
DROP TABLE EQUIPAMENTO
DROP TABLE USUARIO
DROP TABLE USUARIO_CATEGORIA
DELETE FROM SEQUENCE WHERE SEQ_NAME = 'SEQ_GEN'
